---
- name: "Add Proxy Variables to Apache2 Configuration."
  lineinfile:
    path: /etc/{{ webserver_apache_name }}/envvars
    state: present
    mode: 0644
    owner: root
    group: root
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    create: 'true'
  with_items:
    - line: "export http_proxy='{{ common_proxy_string }}'"
      regexp: "^export http_proxy=.*"
    - line: "export https_proxy='{{ common_proxy_string }}'"
      regexp: "^export https_proxy=.*"
    - line: "export no_proxy='localhost{% for proxy_exception in common_proxy_exceptions %}, {{ proxy_exception }}{% endfor %}'"
      regexp: "^export no_proxy=.*"
    - line: "export HTTP_PROXY='{{ common_proxy_string }}'"
      regexp: "^export HTTP_PROXY=.*"
    - line: "export HTTPS_PROXY='{{ common_proxy_string }}'"
      regexp: "^export HTTPS_PROXY=.*"
    - line: "export NO_PROXY='localhost{% for proxy_exception in common_proxy_exceptions %}, {{ proxy_exception }}{% endfor %}'"
      regexp: "^export NO_PROXY=.*"
  when: webserver_apache_name != "None"
