---
- name: Add proxy variables to /etc/bash.bashrc to set Proxy for Bash Shells globally.
  lineinfile:
   path: /etc/bash.bashrc
   state: present
   line: "{{ item.line }}"
   regexp: "{{ item.regexp }}"
   create: yes
  with_items:
    - line: "export http_proxy='http://{{ common_proxy_server }}:{{ common_proxy_port }}'"
      regexp: "^export http_proxy=.*"
    - line: "export https_proxy='http://{{ common_proxy_server }}:{{ common_proxy_port }}'"
      regexp: "^export https_proxy=.*"
    - line: "export no_proxy='localhost{% for proxy_exception in common_proxy_exceptions %}, {{ proxy_exception }}{% endfor %}'"
      regexp: "^export no_proxy=.*"
