---
- name: Prepare state of settings
  set_fact:
    proxy_state: "{{ 'absent' if (common_proxy_dnf_proxy_server == '' or common_proxy_dnf_proxy_port == '') else 'present'}}"
    username_state: "{{ 'absent' if common_proxy_dnf_proxy_username == '' else 'present'}}"
    password_state: "{{ 'absent' if common_proxy_dnf_proxy_password == '' else 'present'}}"


- name: Configure proxy settings for dnf
  ini_file:
    dest: /etc/dnf/dnf.conf
    section: main
    option: proxy
    value: "http://{{ common_proxy_dnf_proxy_server }}:{{ common_proxy_dnf_proxy_port }}"
    state: "{{ proxy_state }}"
    owner: root
    group: root
    mode: 0644
  when: ansible_pkg_mgr == 'dnf'

- name: Configure proxy_username for dnf
  ini_file:
    dest: /etc/dnf/dnf.conf
    section: main
    option: proxy_username
    value: "{{ common_proxy_dnf_proxy_username }}"
    state: "{{ username_state }}"
    owner: root
    group: root
    mode: 0644
    setype: etc_t
  when: ansible_pkg_mgr == 'dnf'

- name: Configure proxy_password for dnf
  ini_file:
    dest: /etc/dnf/dnf.conf
    section: main
    option: proxy_password
    value: "{{ common_proxy_dnf_proxy_password }}"
    state: "{{ password_state }}"
    owner: root
    group: root
    mode: 0644
    setype: etc_t
  when: ansible_pkg_mgr == 'dnf'

- name: Configure proxy settings for yum
  ini_file:
    dest: /etc/yum/yum.conf
    section: main
    option: proxy
    value: "http://{{ common_proxy_dnf_proxy_server }}:{{ common_proxy_dnf_proxy_port }}"
    state: "{{ proxy_state }}"
    owner: root
    group: root
    mode: 0644
    setype: etc_t
  when: ansible_pkg_mgr == 'yum'

- name: Configure proxy_username for yum
  ini_file:
    dest: /etc/yum/yum.conf
    section: main
    option: proxy_username
    state: "{{ username_state }}"
    owner: root
    group: root
    mode: 0644
    setype: etc_t
  when: ansible_pkg_mgr == 'yum'

- name: Configure password for dnf
  ini_file:
    dest: /etc/yum/yum.conf
    section: main
    option: proxy_password
    value: "{{ common_proxy_dnf_proxy_password }}"
    owner: root
    group: root
    mode: 0644
    setype: etc_t
    state: "{{ password_state }}"
  when: ansible_pkg_mgr == 'yum'
