---
- name: "Make sure git is installed."
  package:
    name: git
    state: present

- name: "Configure git to use a Proxy."
  shell: "git config --global http.proxy {{ common_proxy_string }}"
  args:
    warn: 'false'
