---
- name: "Create proxy.sh script in profile.d to set Proxy for interactive Shells globally."
  template:
   dest: /etc/profile.d/99proxy.sh
   src: 99proxy.sh.j2
   owner: root
   group: root
   mode: 0644
  when: ( common_proxy_server | length ) and ( common_proxy_port | length )

- name: "Remove proxy.sh script in profile.d to disable Proxy for interactive Shells globally."
  file:
   dest: /etc/profile.d/99proxy.sh
   state: absent
  when: ( not common_proxy_server | length ) or ( not common_proxy_port | length )
