---
- name: "wgetrc | update /etc/wgetrc with proxy settings."
  lineinfile:
   dest: /etc/wgetrc
   line: "{{ item.line }}"
   regexp: "{{ item.regexp }}"
   create: 'yes'
   owner: root
   group: root
   mode: 0644
  with_items:
   - line: "http_proxy = {{ common_proxy_string }}"
     regexp: "^http_proxy =.*"
   - line: "https_proxy = {{ common_proxy_string }}"
     regexp: "^https_proxy =.*"
